### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thombruce** [thombruce/verse#68]
## Combat

- [x] #53
- [ ] Weapon variety
	- [x] Ballistic cannon (23763184a17542eeec1465e298019fd2845f3ed9)
	- [ ] #69
	- [ ] EMP/Environmental weapon
	- [ ] Railgun (accurate, high damage; longer reload)
	- [ ] Missiles
	    - [ ] Explosive (impact, timed, vicinity)
	    - [ ] Heat-seeking
	    - [ ] AI-assisted (like heat-seeking but more focused - pursues single target, maybe, instead of closest heat-source)
- [ ] Power-ups? E.g. Better accuracy, higher fire rate, increased damage, etc.
- [ ] Enemy variety
- [ ] #52
- [ ] #78

## Careers

- [ ] Asteroid mining
- [ ] Transport/logistics
- [ ] Science/exploration - collecting and analysing samples, gaining knowledge about worlds/entities
    - [ ] Making that research useful/rewarding (perhaps knowledge can be quantified as the player gains it, and individual knowledge units could be reported or sold to others)
    - [ ] One obvious idea is to allow planets to be claimed on discovery - they could then be improved/terraformed and sold to either governments or commercial bodies; the more knowledge you have about a planet, the higher the price you could expect to sell it for as you dress up its worth (consider also allowing the player to omit crucial details - inflating the price of an undesirable planet at the cost of respect and trustworthiness [the more trust and respect you have, the easier you'll be able to find buyers if this is a career path that is desirable to you])

## World

- [x] #51
- [ ] Interior spaces, living quarters
- [ ] Pets
- [ ] Crew
- [ ] Planetary landings
- [ ] #10
    - [ ] #84
- [ ] Megastructures/Engineering/Wormholes and Warp Gates
- [ ] #86

## Story

- [ ] Narrative and dialogue
